### ISSUE TITLE
Remove TIE-GCM load support for `pysat.utils.load_netCDF4`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatModels#114]
**Is your feature request related to a problem? Please describe.**
The location and name of the function to load netCDF data will soon change.  This function is used by the UCAR TIE-GCM instrument in a direct call.  At the moment, an if/else statement checks to see which call should be made.

**Describe the solution you'd like**
Not have if/else statements everywhere.

**Describe alternatives you've considered**
Adding a pysat version limit

**Additional context**
Eventually a pysat version limit will make sense, but for the moment, it's good to support any version of pysat 3.X.

**Comment by jklenzing** [comment]
This applies to sami2py and dineofs too.
