### ISSUE TITLE
BUG/ENH: satellite_view_through_model

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatModels#12]
**Describe the bug**
satellite_view_through_model only works for pandas data and does not update metadata
- assumes that the coordinates are all in the data and not coords

**Describe desired enhancements**

- [x] Change name to be better; i.e. show that it's applicable for ground-based data
- [x] Add optional scaling, so that the interpolated output can be easily compared to the observed data
- [x] Needs more comments (e.g., why is RegularGridInterpolator used, and what restrictions does this place on the model input?)
- [x] Needs unit tests
- [x] Need input tests

**Comment by rstoneback** [comment]
Acknowledged.

**Comment by jklenzing** [comment]
Name change possibility: `interp_model_onto_inst`

**Comment by rstoneback** [comment]
@aburrell 
Current `develop` branch has units scaling in both `instrument_view_through_model` and `instrument_view_irregular_model`. I believe this covers the scaling question at the top?

There are unit tests for the `instrument_view_through_model` function. I am working on the `instrument_altitude_to_model_pressure` method now. I need model data to work with so I'm starting on recreating the most relevant data structures from TIEGCM.

**Comment by rstoneback** [comment]
https://github.com/pysat/pysat/pull/905
