### ISSUE TITLE
ENH: Incorporate ESMPy

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatModels#3]
Migrating from pysat/pysat#177.  From @aburrell.

Different ITM models use different coordinate systems as their reference frame. This are often not compatible with the way measurements are recorded, requiring re-gridding and interpolation. ESMPy is designed specifically for this an could be useful to incorporate.

https://www.earthsystemcog.org/projects/esmpy/

**Comment by aburrell** [comment]
After looking into this, ESMPy needs to be tied to each model in a different way, and so is out of the scope of this repository, at the moment.
