### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatModels#35]
The docs need significant improvement.  Specifically these things:

- [x] GitHub webhook is not integrated (apparently I don't have permission to do this)
- [x] ReadTheDocs link on README needs to be added
- [x] Utilities docstrings not showing up
- [x] Model docstrings not showing up
- [x] Need examples for each of the utility routines (some remaining functions in extract)

**Comment by rstoneback** [comment]
I believe @jklenzing created this repo... When I look under settings he is the only one listed with Admin access. We should decide upon and get access settings sorted out for all the repos.

Just as an FYI I see a readthedocs web hook in settings if that is the hook you are going for.

**Comment by aburrell** [comment]
Yes, I tried to set the web hook in the settings and it didn't work for me.

**Comment by jklenzing** [comment]
Added you both as admins.  Sorry about that.  Assumed things would propagate down from the main package.

**Comment by aburrell** [comment]
I had hoped that would fix the docstrings not showing up, but it didn't :'(

**Comment by rstoneback** [comment]
That is a bummer. Friendly check, do you have autodoc turned on?

http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

On Apr 16, 2020, at 12:44 PM, Angeline Burrell <notifications@github.com> wrote:

﻿

I had hoped that would fix the docstrings not showing up, but it didn't :'(

**Comment by aburrell** [comment]
Thought so, but perhaps another set of eyes would be useful.

________________________________

**Comment by rstoneback** [comment]
Sure. I’ll be back in ‘the office’ shortly and after the call.

On Apr 16, 2020, at 12:50 PM, Angeline Burrell <notifications@github.com> wrote:

﻿

Thought so, but perhaps another set of eyes would be useful.

________________________________

**Comment by rstoneback** [comment]
I see docstrings on my end when I build the docs. This is in both Utilities and Models.

![Screen Shot 2020-04-16 at 1 47 49 PM](https://user-images.githubusercontent.com/3595641/79494596-e50a0200-7fe8-11ea-9941-52e64ce878dc.png)

**Comment by aburrell** [comment]
Yeah, same for me.  That's why I am very confused about their absence on readthedocs.

**Comment by rstoneback** [comment]
slowly catching up :)

**Comment by aburrell** [comment]
Focusing the debugging efforts on the branch with PR #36 is probably the most efficient way to go.

**Comment by rstoneback** [comment]
Does a verify module sound familiar to you? I found this in the readthedocs build log.

WARNING: autodoc: failed to import module 'models.ucar_tiegcm' from module 'pysatModels'; the following exception was raised:
No module named 'verify'
WARNING: autodoc: failed to import module 'utils.match' from module 'pysatModels'; the following exception was raised:
No module named 'verify'
WARNING: autodoc: failed to import module 'utils.extract' from module 'pysatModels'; the following exception was raised:
No module named 'verify'
WARNING: autodoc: failed to import module 'utils.compare' from module 'pysatModels'; the following exception was raised:
No module named 'verify'

**Comment by aburrell** [comment]
that's pyForecastTools... I'm guessing it needs to be included in the requirements.txt?

**Comment by rstoneback** [comment]
sounds reasonable to me

On Apr 16, 2020, at 2:27 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:



that's pyForecastTools... I'm guessing it needs to be included in the requirements.txt?
