### ISSUE TITLE
BUG: sami2py instrument

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatModels#52]
**Describe the bug**
Time in the SAMI2py instrument `sami2py_sami2` is not compatible with pysat because the `time` index is a float and not a time.

**To Reproduce**
```
import datetime as dt
import pysat
import pysatModels as ps_mod

stime = dt.datetime(2019, 1, 1)
sami2 = pysat.Instrument(inst_module=ps_mod.models.sami2py_sami2, tag='test')
sami2.download(stime, stime)
sami2.load(date=stime)

print(sami2)
```

This results in:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-674d1db8a7af> in <module>
----> 1 print(sami2)

~/Programs/Git/pysat/pysat/_instrument.py in __str__(self)
    899             output_str += 'DOY: {:03d}'.format(self.doy) + '\n'
    900             output_str += 'Time range: '
--> 901             output_str += self.index[0].strftime('%d %B %Y %H:%M:%S')
    902             output_str += ' --- '
    903             output_str += self.index[-1].strftime('%d %B %Y %H:%M:%S')+'\n'

AttributeError: 'numpy.float64' object has no attribute 'strftime'
```

If you print out the instrument index, the cause becomes apparent:
```
sami2.index                                                            
Out[13]: 
Float64Index([0.20083333333333334, 0.45083333333333336,  0.7008333333333333,
               0.9508333333333333,  1.2041666666666666,              1.4575],
             dtype='float64', name='time')
```

**Expected behavior**
pysat expects the index to be a datetime or numpy datetime64 object, so the load routine needs to take the load time and add it to the model time, obtaining an appropriate time index.

**Desktop (please complete the following information):**
 - OS: OS X
 - Version Python 3.7, both pysat develop branches

**Additional context**
Should have caught this in the last PR :(

**Comment by jklenzing** [comment]
The issue is I need to convert time to a datetime object.  
```
    data['time'] = [start_time + pds.DateOffset(hours=val)
                    for val in data['ut'].values]
```
The issue being that I need a start time, which is not currently availabIe as far as I can tell.  I can add this to the metadata as a patch in sami2py.  For a temporary patch here, I can hardwire the start time to be the test date if needed.

**Comment by aburrell** [comment]
Yes, that will work for now.
