### ISSUE TITLE
ENH: basic functionality

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatModels#6]
This module needs several basic things:
- [x] setup.py
- [x] documentation directory with basic description and API
- [x] Travis CI testing
- [x] Appveyor/Windows CI testing
- [x] unit tests for all modules

**Comment by jklenzing** [comment]
Setup and CI are in develop branch

**Comment by aburrell** [comment]
To figure out where to devote unit testing efforts, check out: https://coveralls.io/github/pysat/pysatModels?branch=develop

**Comment by aburrell** [comment]
@rstoneback the only unit tests left now are the ones for your routines.

**Comment by rstoneback** [comment]
Thanks for the reminder today at the meeting @aburrell though apologies this fell of my plate. On my list for tomorrow.

**Comment by rstoneback** [comment]
I started the unit tests over in draft pull #84.
